version: "3.8"

services:
  db:
    image: postgres:16
    container_name: huertoup_db
    restart: always
    environment:
      POSTGRES_DB: huertoup
      POSTGRES_USER: jdl
      POSTGRES_PASSWORD: proyecto123
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
